package com.credit.model.rate;

import java.util.Date;

public class AgcBase {

	private String agcId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcOrgId
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private String agcOrgId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcCnName
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private String agcCnName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcEnName
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private String agcEnName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcNature
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private Integer agcNature;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcFoundingDate
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private Date agcFoundingDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcRegisType
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private Integer agcRegisType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcRagisNum
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private String agcRagisNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcRagisDate
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private Date agcRagisDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcBizLicsExpDate
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private Date agcBizLicsExpDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcRegisAddr
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private String agcRegisAddr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcMunicpPrv
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private Integer agcMunicpPrv;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcMunicpCity
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private Integer agcMunicpCity;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcMunicpDistr
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private Integer agcMunicpDistr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcAbrdInvstRegisNum
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private String agcAbrdInvstRegisNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcNTaxCertiNum
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private String agcNTaxCertiNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcLTaxCertiNum
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private String agcLTaxCertiNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcLoanCardCode
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private String agcLoanCardCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcDefaultRateCode
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private Long agcDefaultRateCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcLegleRepr
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private String agcLegleRepr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcLegleReprIDType
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private Integer agcLegleReprIDType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcLegleReprIDNum
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private String agcLegleReprIDNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcQualification
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private String agcQualification;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcBizScope
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private String agcBizScope;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcContactName
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private String agcContactName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcContactNumber
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private String agcContactNumber;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcFax
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private String agcFax;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcHQAddress
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private String agcHQAddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcHQCode
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private Integer agcHQCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcPostalAddr
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private String agcPostalAddr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcEmail
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private String agcEmail;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcWebsite
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private String agcWebsite;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcListedLoacation
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private String agcListedLoacation;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcRegisCapital
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private Double agcRegisCapital;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcBizArea
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private Double agcBizArea;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcCrewSize
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private Integer agcCrewSize;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_base_info.agcRatingProfes
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	private Integer agcRatingProfes;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcOrgId
	 * 
	 * @return the value of agc_base_info.agcOrgId
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public String getAgcOrgId() {
		return agcOrgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcOrgId
	 * 
	 * @param agcOrgId
	 *            the value for agc_base_info.agcOrgId
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcOrgId(String agcOrgId) {
		this.agcOrgId = agcOrgId == null ? null : agcOrgId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcCnName
	 * 
	 * @return the value of agc_base_info.agcCnName
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public String getAgcCnName() {
		return agcCnName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcCnName
	 * 
	 * @param agcCnName
	 *            the value for agc_base_info.agcCnName
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcCnName(String agcCnName) {
		this.agcCnName = agcCnName == null ? null : agcCnName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcEnName
	 * 
	 * @return the value of agc_base_info.agcEnName
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public String getAgcEnName() {
		return agcEnName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcEnName
	 * 
	 * @param agcEnName
	 *            the value for agc_base_info.agcEnName
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcEnName(String agcEnName) {
		this.agcEnName = agcEnName == null ? null : agcEnName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcNature
	 * 
	 * @return the value of agc_base_info.agcNature
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public Integer getAgcNature() {
		return agcNature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcNature
	 * 
	 * @param agcNature
	 *            the value for agc_base_info.agcNature
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcNature(Integer agcNature) {
		this.agcNature = agcNature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcFoundingDate
	 * 
	 * @return the value of agc_base_info.agcFoundingDate
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public Date getAgcFoundingDate() {
		return agcFoundingDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcFoundingDate
	 * 
	 * @param agcFoundingDate
	 *            the value for agc_base_info.agcFoundingDate
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcFoundingDate(Date agcFoundingDate) {
		this.agcFoundingDate = agcFoundingDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcRegisType
	 * 
	 * @return the value of agc_base_info.agcRegisType
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public Integer getAgcRegisType() {
		return agcRegisType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcRegisType
	 * 
	 * @param agcRegisType
	 *            the value for agc_base_info.agcRegisType
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcRegisType(Integer agcRegisType) {
		this.agcRegisType = agcRegisType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcRagisNum
	 * 
	 * @return the value of agc_base_info.agcRagisNum
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public String getAgcRagisNum() {
		return agcRagisNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcRagisNum
	 * 
	 * @param agcRagisNum
	 *            the value for agc_base_info.agcRagisNum
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcRagisNum(String agcRagisNum) {
		this.agcRagisNum = agcRagisNum == null ? null : agcRagisNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcRagisDate
	 * 
	 * @return the value of agc_base_info.agcRagisDate
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public Date getAgcRagisDate() {
		return agcRagisDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcRagisDate
	 * 
	 * @param agcRagisDate
	 *            the value for agc_base_info.agcRagisDate
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcRagisDate(Date agcRagisDate) {
		this.agcRagisDate = agcRagisDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcBizLicsExpDate
	 * 
	 * @return the value of agc_base_info.agcBizLicsExpDate
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public Date getAgcBizLicsExpDate() {
		return agcBizLicsExpDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcBizLicsExpDate
	 * 
	 * @param agcBizLicsExpDate
	 *            the value for agc_base_info.agcBizLicsExpDate
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcBizLicsExpDate(Date agcBizLicsExpDate) {
		this.agcBizLicsExpDate = agcBizLicsExpDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcRegisAddr
	 * 
	 * @return the value of agc_base_info.agcRegisAddr
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public String getAgcRegisAddr() {
		return agcRegisAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcRegisAddr
	 * 
	 * @param agcRegisAddr
	 *            the value for agc_base_info.agcRegisAddr
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcRegisAddr(String agcRegisAddr) {
		this.agcRegisAddr = agcRegisAddr == null ? null : agcRegisAddr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcMunicpPrv
	 * 
	 * @return the value of agc_base_info.agcMunicpPrv
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public Integer getAgcMunicpPrv() {
		return agcMunicpPrv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcMunicpPrv
	 * 
	 * @param agcMunicpPrv
	 *            the value for agc_base_info.agcMunicpPrv
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcMunicpPrv(Integer agcMunicpPrv) {
		this.agcMunicpPrv = agcMunicpPrv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcMunicpCity
	 * 
	 * @return the value of agc_base_info.agcMunicpCity
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public Integer getAgcMunicpCity() {
		return agcMunicpCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcMunicpCity
	 * 
	 * @param agcMunicpCity
	 *            the value for agc_base_info.agcMunicpCity
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcMunicpCity(Integer agcMunicpCity) {
		this.agcMunicpCity = agcMunicpCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcMunicpDistr
	 * 
	 * @return the value of agc_base_info.agcMunicpDistr
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public Integer getAgcMunicpDistr() {
		return agcMunicpDistr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcMunicpDistr
	 * 
	 * @param agcMunicpDistr
	 *            the value for agc_base_info.agcMunicpDistr
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcMunicpDistr(Integer agcMunicpDistr) {
		this.agcMunicpDistr = agcMunicpDistr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcAbrdInvstRegisNum
	 * 
	 * @return the value of agc_base_info.agcAbrdInvstRegisNum
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public String getAgcAbrdInvstRegisNum() {
		return agcAbrdInvstRegisNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcAbrdInvstRegisNum
	 * 
	 * @param agcAbrdInvstRegisNum
	 *            the value for agc_base_info.agcAbrdInvstRegisNum
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcAbrdInvstRegisNum(String agcAbrdInvstRegisNum) {
		this.agcAbrdInvstRegisNum = agcAbrdInvstRegisNum == null ? null : agcAbrdInvstRegisNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcNTaxCertiNum
	 * 
	 * @return the value of agc_base_info.agcNTaxCertiNum
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public String getAgcNTaxCertiNum() {
		return agcNTaxCertiNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcNTaxCertiNum
	 * 
	 * @param agcNTaxCertiNum
	 *            the value for agc_base_info.agcNTaxCertiNum
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcNTaxCertiNum(String agcNTaxCertiNum) {
		this.agcNTaxCertiNum = agcNTaxCertiNum == null ? null : agcNTaxCertiNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcLTaxCertiNum
	 * 
	 * @return the value of agc_base_info.agcLTaxCertiNum
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public String getAgcLTaxCertiNum() {
		return agcLTaxCertiNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcLTaxCertiNum
	 * 
	 * @param agcLTaxCertiNum
	 *            the value for agc_base_info.agcLTaxCertiNum
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcLTaxCertiNum(String agcLTaxCertiNum) {
		this.agcLTaxCertiNum = agcLTaxCertiNum == null ? null : agcLTaxCertiNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcLoanCardCode
	 * 
	 * @return the value of agc_base_info.agcLoanCardCode
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public String getAgcLoanCardCode() {
		return agcLoanCardCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcLoanCardCode
	 * 
	 * @param agcLoanCardCode
	 *            the value for agc_base_info.agcLoanCardCode
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcLoanCardCode(String agcLoanCardCode) {
		this.agcLoanCardCode = agcLoanCardCode == null ? null : agcLoanCardCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcDefaultRateCode
	 * 
	 * @return the value of agc_base_info.agcDefaultRateCode
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public Long getAgcDefaultRateCode() {
		return agcDefaultRateCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcDefaultRateCode
	 * 
	 * @param agcDefaultRateCode
	 *            the value for agc_base_info.agcDefaultRateCode
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcDefaultRateCode(Long agcDefaultRateCode) {
		this.agcDefaultRateCode = agcDefaultRateCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcLegleRepr
	 * 
	 * @return the value of agc_base_info.agcLegleRepr
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public String getAgcLegleRepr() {
		return agcLegleRepr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcLegleRepr
	 * 
	 * @param agcLegleRepr
	 *            the value for agc_base_info.agcLegleRepr
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcLegleRepr(String agcLegleRepr) {
		this.agcLegleRepr = agcLegleRepr == null ? null : agcLegleRepr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcLegleReprIDType
	 * 
	 * @return the value of agc_base_info.agcLegleReprIDType
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public Integer getAgcLegleReprIDType() {
		return agcLegleReprIDType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcLegleReprIDType
	 * 
	 * @param agcLegleReprIDType
	 *            the value for agc_base_info.agcLegleReprIDType
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcLegleReprIDType(Integer agcLegleReprIDType) {
		this.agcLegleReprIDType = agcLegleReprIDType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcLegleReprIDNum
	 * 
	 * @return the value of agc_base_info.agcLegleReprIDNum
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public String getAgcLegleReprIDNum() {
		return agcLegleReprIDNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcLegleReprIDNum
	 * 
	 * @param agcLegleReprIDNum
	 *            the value for agc_base_info.agcLegleReprIDNum
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcLegleReprIDNum(String agcLegleReprIDNum) {
		this.agcLegleReprIDNum = agcLegleReprIDNum == null ? null : agcLegleReprIDNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcQualification
	 * 
	 * @return the value of agc_base_info.agcQualification
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public String getAgcQualification() {
		return agcQualification;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcQualification
	 * 
	 * @param agcQualification
	 *            the value for agc_base_info.agcQualification
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcQualification(String agcQualification) {
		this.agcQualification = agcQualification == null ? null : agcQualification.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcBizScope
	 * 
	 * @return the value of agc_base_info.agcBizScope
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public String getAgcBizScope() {
		return agcBizScope;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcBizScope
	 * 
	 * @param agcBizScope
	 *            the value for agc_base_info.agcBizScope
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcBizScope(String agcBizScope) {
		this.agcBizScope = agcBizScope == null ? null : agcBizScope.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcContactName
	 * 
	 * @return the value of agc_base_info.agcContactName
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public String getAgcContactName() {
		return agcContactName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcContactName
	 * 
	 * @param agcContactName
	 *            the value for agc_base_info.agcContactName
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcContactName(String agcContactName) {
		this.agcContactName = agcContactName == null ? null : agcContactName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcContactNumber
	 * 
	 * @return the value of agc_base_info.agcContactNumber
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public String getAgcContactNumber() {
		return agcContactNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcContactNumber
	 * 
	 * @param agcContactNumber
	 *            the value for agc_base_info.agcContactNumber
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcContactNumber(String agcContactNumber) {
		this.agcContactNumber = agcContactNumber == null ? null : agcContactNumber.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcFax
	 * 
	 * @return the value of agc_base_info.agcFax
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public String getAgcFax() {
		return agcFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcFax
	 * 
	 * @param agcFax
	 *            the value for agc_base_info.agcFax
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcFax(String agcFax) {
		this.agcFax = agcFax == null ? null : agcFax.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcHQAddress
	 * 
	 * @return the value of agc_base_info.agcHQAddress
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public String getAgcHQAddress() {
		return agcHQAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcHQAddress
	 * 
	 * @param agcHQAddress
	 *            the value for agc_base_info.agcHQAddress
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcHQAddress(String agcHQAddress) {
		this.agcHQAddress = agcHQAddress == null ? null : agcHQAddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcHQCode
	 * 
	 * @return the value of agc_base_info.agcHQCode
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public Integer getAgcHQCode() {
		return agcHQCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcHQCode
	 * 
	 * @param agcHQCode
	 *            the value for agc_base_info.agcHQCode
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcHQCode(Integer agcHQCode) {
		this.agcHQCode = agcHQCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcPostalAddr
	 * 
	 * @return the value of agc_base_info.agcPostalAddr
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public String getAgcPostalAddr() {
		return agcPostalAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcPostalAddr
	 * 
	 * @param agcPostalAddr
	 *            the value for agc_base_info.agcPostalAddr
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcPostalAddr(String agcPostalAddr) {
		this.agcPostalAddr = agcPostalAddr == null ? null : agcPostalAddr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcEmail
	 * 
	 * @return the value of agc_base_info.agcEmail
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public String getAgcEmail() {
		return agcEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcEmail
	 * 
	 * @param agcEmail
	 *            the value for agc_base_info.agcEmail
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcEmail(String agcEmail) {
		this.agcEmail = agcEmail == null ? null : agcEmail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcWebsite
	 * 
	 * @return the value of agc_base_info.agcWebsite
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public String getAgcWebsite() {
		return agcWebsite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcWebsite
	 * 
	 * @param agcWebsite
	 *            the value for agc_base_info.agcWebsite
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcWebsite(String agcWebsite) {
		this.agcWebsite = agcWebsite == null ? null : agcWebsite.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcListedLoacation
	 * 
	 * @return the value of agc_base_info.agcListedLoacation
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public String getAgcListedLoacation() {
		return agcListedLoacation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcListedLoacation
	 * 
	 * @param agcListedLoacation
	 *            the value for agc_base_info.agcListedLoacation
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcListedLoacation(String agcListedLoacation) {
		this.agcListedLoacation = agcListedLoacation == null ? null : agcListedLoacation.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcRegisCapital
	 * 
	 * @return the value of agc_base_info.agcRegisCapital
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public Double getAgcRegisCapital() {
		return agcRegisCapital;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcRegisCapital
	 * 
	 * @param agcRegisCapital
	 *            the value for agc_base_info.agcRegisCapital
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcRegisCapital(Double agcRegisCapital) {
		this.agcRegisCapital = agcRegisCapital;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcBizArea
	 * 
	 * @return the value of agc_base_info.agcBizArea
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public Double getAgcBizArea() {
		return agcBizArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcBizArea
	 * 
	 * @param agcBizArea
	 *            the value for agc_base_info.agcBizArea
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcBizArea(Double agcBizArea) {
		this.agcBizArea = agcBizArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcCrewSize
	 * 
	 * @return the value of agc_base_info.agcCrewSize
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public Integer getAgcCrewSize() {
		return agcCrewSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcCrewSize
	 * 
	 * @param agcCrewSize
	 *            the value for agc_base_info.agcCrewSize
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcCrewSize(Integer agcCrewSize) {
		this.agcCrewSize = agcCrewSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_base_info.agcRatingProfes
	 * 
	 * @return the value of agc_base_info.agcRatingProfes
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public Integer getAgcRatingProfes() {
		return agcRatingProfes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_base_info.agcRatingProfes
	 * 
	 * @param agcRatingProfes
	 *            the value for agc_base_info.agcRatingProfes
	 * 
	 * @mbggenerated Thu Nov 08 17:31:25 GMT+08:00 2012
	 */
	public void setAgcRatingProfes(Integer agcRatingProfes) {
		this.agcRatingProfes = agcRatingProfes;
	}

	public String getAgcId() {
		return agcId;
	}

	public void setAgcId(String agcId) {
		this.agcId = agcId;
	}
}