package com.credit.model.rate;

import com.bluecloud.persistence.pojo.BaseBO;

public class AgcFinacial extends BaseBO {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcFinaceId
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private String agcFinaceId;

	private String agcCnName;

	private String agcId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcOrgId
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private String agcOrgId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcRptYear
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private Integer agcRptYear;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcTotalAssets
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private Double agcTotalAssets;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcMoneyFunds
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private Double agcMoneyFunds;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcFixedAssets
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private Double agcFixedAssets;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcOwnerRights
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private Double agcOwnerRights;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcUndisProfits
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private Double agcUndisProfits;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcTotalRatIncm
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private Double agcTotalRatIncm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcRatIncm
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private Double agcRatIncm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcBorVentRatIncm
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private Double agcBorVentRatIncm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcGuaraRatIncm
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private Double agcGuaraRatIncm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcFinancRatIncm
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private Double agcFinancRatIncm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcTBoundsRatIncm
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private Double agcTBoundsRatIncm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcStrctFinancRatIncm
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private Double agcStrctFinancRatIncm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcSBndRatIncm
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private Double agcSBndRatIncm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcMainBizCost
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private Double agcMainBizCost;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcMainBizProfit
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private Double agcMainBizProfit;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcFinaExpense
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private Double agcFinaExpense;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcAdmExpense
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private Double agcAdmExpense;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcBizTaxAndAnn
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private Double agcBizTaxAndAnn;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcTotalProfit
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private Double agcTotalProfit;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcIncmTax
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private Double agcIncmTax;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcNetProfit
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private Double agcNetProfit;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcAccFirmName
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private String agcAccFirmName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_finacial_data.agcAccFirmOpin
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	private String agcAccFirmOpin;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_finacial_data.agcOrgId
	 * 
	 * @return the value of agc_finacial_data.agcOrgId
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public String getAgcOrgId() {
		return agcOrgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_finacial_data.agcOrgId
	 * 
	 * @param agcOrgId
	 *            the value for agc_finacial_data.agcOrgId
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public void setAgcOrgId(String agcOrgId) {
		this.agcOrgId = agcOrgId == null ? null : agcOrgId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_finacial_data.agcRptYear
	 * 
	 * @return the value of agc_finacial_data.agcRptYear
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public Integer getAgcRptYear() {
		return agcRptYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_finacial_data.agcRptYear
	 * 
	 * @param agcRptYear
	 *            the value for agc_finacial_data.agcRptYear
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public void setAgcRptYear(Integer agcRptYear) {
		this.agcRptYear = agcRptYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_finacial_data.agcTotalAssets
	 * 
	 * @return the value of agc_finacial_data.agcTotalAssets
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public Double getAgcTotalAssets() {
		return agcTotalAssets;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_finacial_data.agcTotalAssets
	 * 
	 * @param agcTotalAssets
	 *            the value for agc_finacial_data.agcTotalAssets
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public void setAgcTotalAssets(Double agcTotalAssets) {
		this.agcTotalAssets = agcTotalAssets;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_finacial_data.agcMoneyFunds
	 * 
	 * @return the value of agc_finacial_data.agcMoneyFunds
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public Double getAgcMoneyFunds() {
		return agcMoneyFunds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_finacial_data.agcMoneyFunds
	 * 
	 * @param agcMoneyFunds
	 *            the value for agc_finacial_data.agcMoneyFunds
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public void setAgcMoneyFunds(Double agcMoneyFunds) {
		this.agcMoneyFunds = agcMoneyFunds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_finacial_data.agcFixedAssets
	 * 
	 * @return the value of agc_finacial_data.agcFixedAssets
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public Double getAgcFixedAssets() {
		return agcFixedAssets;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_finacial_data.agcFixedAssets
	 * 
	 * @param agcFixedAssets
	 *            the value for agc_finacial_data.agcFixedAssets
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public void setAgcFixedAssets(Double agcFixedAssets) {
		this.agcFixedAssets = agcFixedAssets;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_finacial_data.agcOwnerRights
	 * 
	 * @return the value of agc_finacial_data.agcOwnerRights
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public Double getAgcOwnerRights() {
		return agcOwnerRights;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_finacial_data.agcOwnerRights
	 * 
	 * @param agcOwnerRights
	 *            the value for agc_finacial_data.agcOwnerRights
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public void setAgcOwnerRights(Double agcOwnerRights) {
		this.agcOwnerRights = agcOwnerRights;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_finacial_data.agcUndisProfits
	 * 
	 * @return the value of agc_finacial_data.agcUndisProfits
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public Double getAgcUndisProfits() {
		return agcUndisProfits;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_finacial_data.agcUndisProfits
	 * 
	 * @param agcUndisProfits
	 *            the value for agc_finacial_data.agcUndisProfits
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public void setAgcUndisProfits(Double agcUndisProfits) {
		this.agcUndisProfits = agcUndisProfits;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_finacial_data.agcTotalRatIncm
	 * 
	 * @return the value of agc_finacial_data.agcTotalRatIncm
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public Double getAgcTotalRatIncm() {
		return agcTotalRatIncm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_finacial_data.agcTotalRatIncm
	 * 
	 * @param agcTotalRatIncm
	 *            the value for agc_finacial_data.agcTotalRatIncm
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public void setAgcTotalRatIncm(Double agcTotalRatIncm) {
		this.agcTotalRatIncm = agcTotalRatIncm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_finacial_data.agcRatIncm
	 * 
	 * @return the value of agc_finacial_data.agcRatIncm
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public Double getAgcRatIncm() {
		return agcRatIncm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_finacial_data.agcRatIncm
	 * 
	 * @param agcRatIncm
	 *            the value for agc_finacial_data.agcRatIncm
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public void setAgcRatIncm(Double agcRatIncm) {
		this.agcRatIncm = agcRatIncm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_finacial_data.agcBorVentRatIncm
	 * 
	 * @return the value of agc_finacial_data.agcBorVentRatIncm
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public Double getAgcBorVentRatIncm() {
		return agcBorVentRatIncm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_finacial_data.agcBorVentRatIncm
	 * 
	 * @param agcBorVentRatIncm
	 *            the value for agc_finacial_data.agcBorVentRatIncm
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public void setAgcBorVentRatIncm(Double agcBorVentRatIncm) {
		this.agcBorVentRatIncm = agcBorVentRatIncm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_finacial_data.agcGuaraRatIncm
	 * 
	 * @return the value of agc_finacial_data.agcGuaraRatIncm
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public Double getAgcGuaraRatIncm() {
		return agcGuaraRatIncm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_finacial_data.agcGuaraRatIncm
	 * 
	 * @param agcGuaraRatIncm
	 *            the value for agc_finacial_data.agcGuaraRatIncm
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public void setAgcGuaraRatIncm(Double agcGuaraRatIncm) {
		this.agcGuaraRatIncm = agcGuaraRatIncm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_finacial_data.agcFinancRatIncm
	 * 
	 * @return the value of agc_finacial_data.agcFinancRatIncm
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public Double getAgcFinancRatIncm() {
		return agcFinancRatIncm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_finacial_data.agcFinancRatIncm
	 * 
	 * @param agcFinancRatIncm
	 *            the value for agc_finacial_data.agcFinancRatIncm
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public void setAgcFinancRatIncm(Double agcFinancRatIncm) {
		this.agcFinancRatIncm = agcFinancRatIncm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_finacial_data.agcTBoundsRatIncm
	 * 
	 * @return the value of agc_finacial_data.agcTBoundsRatIncm
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public Double getAgcTBoundsRatIncm() {
		return agcTBoundsRatIncm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_finacial_data.agcTBoundsRatIncm
	 * 
	 * @param agcTBoundsRatIncm
	 *            the value for agc_finacial_data.agcTBoundsRatIncm
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public void setAgcTBoundsRatIncm(Double agcTBoundsRatIncm) {
		this.agcTBoundsRatIncm = agcTBoundsRatIncm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_finacial_data.agcStrctFinancRatIncm
	 * 
	 * @return the value of agc_finacial_data.agcStrctFinancRatIncm
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public Double getAgcStrctFinancRatIncm() {
		return agcStrctFinancRatIncm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_finacial_data.agcStrctFinancRatIncm
	 * 
	 * @param agcStrctFinancRatIncm
	 *            the value for agc_finacial_data.agcStrctFinancRatIncm
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public void setAgcStrctFinancRatIncm(Double agcStrctFinancRatIncm) {
		this.agcStrctFinancRatIncm = agcStrctFinancRatIncm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_finacial_data.agcSBndRatIncm
	 * 
	 * @return the value of agc_finacial_data.agcSBndRatIncm
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public Double getAgcSBndRatIncm() {
		return agcSBndRatIncm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_finacial_data.agcSBndRatIncm
	 * 
	 * @param agcSBndRatIncm
	 *            the value for agc_finacial_data.agcSBndRatIncm
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public void setAgcSBndRatIncm(Double agcSBndRatIncm) {
		this.agcSBndRatIncm = agcSBndRatIncm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_finacial_data.agcMainBizCost
	 * 
	 * @return the value of agc_finacial_data.agcMainBizCost
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public Double getAgcMainBizCost() {
		return agcMainBizCost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_finacial_data.agcMainBizCost
	 * 
	 * @param agcMainBizCost
	 *            the value for agc_finacial_data.agcMainBizCost
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public void setAgcMainBizCost(Double agcMainBizCost) {
		this.agcMainBizCost = agcMainBizCost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_finacial_data.agcMainBizProfit
	 * 
	 * @return the value of agc_finacial_data.agcMainBizProfit
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public Double getAgcMainBizProfit() {
		return agcMainBizProfit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_finacial_data.agcMainBizProfit
	 * 
	 * @param agcMainBizProfit
	 *            the value for agc_finacial_data.agcMainBizProfit
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public void setAgcMainBizProfit(Double agcMainBizProfit) {
		this.agcMainBizProfit = agcMainBizProfit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_finacial_data.agcFinaExpense
	 * 
	 * @return the value of agc_finacial_data.agcFinaExpense
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public Double getAgcFinaExpense() {
		return agcFinaExpense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_finacial_data.agcFinaExpense
	 * 
	 * @param agcFinaExpense
	 *            the value for agc_finacial_data.agcFinaExpense
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public void setAgcFinaExpense(Double agcFinaExpense) {
		this.agcFinaExpense = agcFinaExpense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_finacial_data.agcAdmExpense
	 * 
	 * @return the value of agc_finacial_data.agcAdmExpense
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public Double getAgcAdmExpense() {
		return agcAdmExpense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_finacial_data.agcAdmExpense
	 * 
	 * @param agcAdmExpense
	 *            the value for agc_finacial_data.agcAdmExpense
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public void setAgcAdmExpense(Double agcAdmExpense) {
		this.agcAdmExpense = agcAdmExpense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_finacial_data.agcBizTaxAndAnn
	 * 
	 * @return the value of agc_finacial_data.agcBizTaxAndAnn
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public Double getAgcBizTaxAndAnn() {
		return agcBizTaxAndAnn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_finacial_data.agcBizTaxAndAnn
	 * 
	 * @param agcBizTaxAndAnn
	 *            the value for agc_finacial_data.agcBizTaxAndAnn
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public void setAgcBizTaxAndAnn(Double agcBizTaxAndAnn) {
		this.agcBizTaxAndAnn = agcBizTaxAndAnn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_finacial_data.agcTotalProfit
	 * 
	 * @return the value of agc_finacial_data.agcTotalProfit
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public Double getAgcTotalProfit() {
		return agcTotalProfit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_finacial_data.agcTotalProfit
	 * 
	 * @param agcTotalProfit
	 *            the value for agc_finacial_data.agcTotalProfit
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public void setAgcTotalProfit(Double agcTotalProfit) {
		this.agcTotalProfit = agcTotalProfit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_finacial_data.agcIncmTax
	 * 
	 * @return the value of agc_finacial_data.agcIncmTax
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public Double getAgcIncmTax() {
		return agcIncmTax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_finacial_data.agcIncmTax
	 * 
	 * @param agcIncmTax
	 *            the value for agc_finacial_data.agcIncmTax
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public void setAgcIncmTax(Double agcIncmTax) {
		this.agcIncmTax = agcIncmTax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_finacial_data.agcNetProfit
	 * 
	 * @return the value of agc_finacial_data.agcNetProfit
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public Double getAgcNetProfit() {
		return agcNetProfit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_finacial_data.agcNetProfit
	 * 
	 * @param agcNetProfit
	 *            the value for agc_finacial_data.agcNetProfit
	 * 
	 * @mbggenerated Tue Nov 13 21:22:57 GMT+08:00 2012
	 */
	public void setAgcNetProfit(Double agcNetProfit) {
		this.agcNetProfit = agcNetProfit;
	}

	public String getAgcAccFirmName() {
		return agcAccFirmName;
	}

	public void setAgcAccFirmName(String agcAccFirmName) {
		this.agcAccFirmName = agcAccFirmName == null ? null : agcAccFirmName.trim();
	}

	public String getAgcAccFirmOpin() {
		return agcAccFirmOpin;
	}

	public void setAgcAccFirmOpin(String agcAccFirmOpin) {
		this.agcAccFirmOpin = agcAccFirmOpin == null ? null : agcAccFirmOpin.trim();
	}

	@Override
	protected String getPKName() {
		return getAgcFinaceId();
	}

	public String getAgcCnName() {
		return agcCnName;
	}

	public void setAgcCnName(String agcCnName) {
		this.agcCnName = agcCnName;
	}

	public String getAgcFinaceId() {
		return agcFinaceId;
	}

	public void setAgcFinaceId(String agcFinaceId) {
		this.agcFinaceId = agcFinaceId;
	}

	public String getAgcId() {
		return agcId;
	}

	public void setAgcId(String agcId) {
		this.agcId = agcId;
	}
}