package com.credit.model.rate;

import java.util.Date;

public class AgcProfessional {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_professional.agcProId
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	private String agcProId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_professional.agcId
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	private String agcId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_professional.agcProName
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	private String agcProName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_professional.agcProIDType
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	private Integer agcProIDType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_professional.agcProIDNum
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	private String agcProIDNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_professional.agcProGender
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	private Integer agcProGender;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_professional.agcProBirthday
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	private Date agcProBirthday;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_professional.agcProHighestEdu
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	private Integer agcProHighestEdu;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_professional.agcProWorkingLife
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	private Integer agcProWorkingLife;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_professional.agcProCertiType
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	private Integer agcProCertiType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_professional.agcProCertiNum
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	private String agcProCertiNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_professional.agcProCertiGrantAuth
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	private String agcProCertiGrantAuth;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_professional.agcProCertiObtDate
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	private Date agcProCertiObtDate;

	private String agcCnName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_professional.agcProCertiStatus
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	private Integer agcProCertiStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_professional.agcProOtherCertis
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	private Date agcProOtherCertis;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_professional.agcProRewdPunish
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	private String agcProRewdPunish;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column agc_professional.agcProResume
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	private String agcProResume;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_professional.agcProName
	 * 
	 * @return the value of agc_professional.agcProName
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public String getAgcProName() {
		return agcProName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_professional.agcProName
	 * 
	 * @param agcProName
	 *            the value for agc_professional.agcProName
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public void setAgcProName(String agcProName) {
		this.agcProName = agcProName == null ? null : agcProName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_professional.agcProIDType
	 * 
	 * @return the value of agc_professional.agcProIDType
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public Integer getAgcProIDType() {
		return agcProIDType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_professional.agcProIDType
	 * 
	 * @param agcProIDType
	 *            the value for agc_professional.agcProIDType
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public void setAgcProIDType(Integer agcProIDType) {
		this.agcProIDType = agcProIDType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_professional.agcProIDNum
	 * 
	 * @return the value of agc_professional.agcProIDNum
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public String getAgcProIDNum() {
		return agcProIDNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_professional.agcProIDNum
	 * 
	 * @param agcProIDNum
	 *            the value for agc_professional.agcProIDNum
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public void setAgcProIDNum(String agcProIDNum) {
		this.agcProIDNum = agcProIDNum == null ? null : agcProIDNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_professional.agcProGender
	 * 
	 * @return the value of agc_professional.agcProGender
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public Integer getAgcProGender() {
		return agcProGender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_professional.agcProGender
	 * 
	 * @param agcProGender
	 *            the value for agc_professional.agcProGender
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public void setAgcProGender(Integer agcProGender) {
		this.agcProGender = agcProGender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_professional.agcProBirthday
	 * 
	 * @return the value of agc_professional.agcProBirthday
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public Date getAgcProBirthday() {
		return agcProBirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_professional.agcProBirthday
	 * 
	 * @param agcProBirthday
	 *            the value for agc_professional.agcProBirthday
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public void setAgcProBirthday(Date agcProBirthday) {
		this.agcProBirthday = agcProBirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_professional.agcProHighestEdu
	 * 
	 * @return the value of agc_professional.agcProHighestEdu
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public Integer getAgcProHighestEdu() {
		return agcProHighestEdu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_professional.agcProHighestEdu
	 * 
	 * @param agcProHighestEdu
	 *            the value for agc_professional.agcProHighestEdu
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public void setAgcProHighestEdu(Integer agcProHighestEdu) {
		this.agcProHighestEdu = agcProHighestEdu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_professional.agcProWorkingLife
	 * 
	 * @return the value of agc_professional.agcProWorkingLife
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public Integer getAgcProWorkingLife() {
		return agcProWorkingLife;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_professional.agcProWorkingLife
	 * 
	 * @param agcProWorkingLife
	 *            the value for agc_professional.agcProWorkingLife
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public void setAgcProWorkingLife(Integer agcProWorkingLife) {
		this.agcProWorkingLife = agcProWorkingLife;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_professional.agcProCertiType
	 * 
	 * @return the value of agc_professional.agcProCertiType
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public Integer getAgcProCertiType() {
		return agcProCertiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_professional.agcProCertiType
	 * 
	 * @param agcProCertiType
	 *            the value for agc_professional.agcProCertiType
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public void setAgcProCertiType(Integer agcProCertiType) {
		this.agcProCertiType = agcProCertiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_professional.agcProCertiNum
	 * 
	 * @return the value of agc_professional.agcProCertiNum
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public String getAgcProCertiNum() {
		return agcProCertiNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_professional.agcProCertiNum
	 * 
	 * @param agcProCertiNum
	 *            the value for agc_professional.agcProCertiNum
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public void setAgcProCertiNum(String agcProCertiNum) {
		this.agcProCertiNum = agcProCertiNum == null ? null : agcProCertiNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_professional.agcProCertiGrantAuth
	 * 
	 * @return the value of agc_professional.agcProCertiGrantAuth
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public String getAgcProCertiGrantAuth() {
		return agcProCertiGrantAuth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_professional.agcProCertiGrantAuth
	 * 
	 * @param agcProCertiGrantAuth
	 *            the value for agc_professional.agcProCertiGrantAuth
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public void setAgcProCertiGrantAuth(String agcProCertiGrantAuth) {
		this.agcProCertiGrantAuth = agcProCertiGrantAuth == null ? null : agcProCertiGrantAuth.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_professional.agcProCertiObtDate
	 * 
	 * @return the value of agc_professional.agcProCertiObtDate
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public Date getAgcProCertiObtDate() {
		return agcProCertiObtDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_professional.agcProCertiObtDate
	 * 
	 * @param agcProCertiObtDate
	 *            the value for agc_professional.agcProCertiObtDate
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public void setAgcProCertiObtDate(Date agcProCertiObtDate) {
		this.agcProCertiObtDate = agcProCertiObtDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_professional.agcProCertiStatus
	 * 
	 * @return the value of agc_professional.agcProCertiStatus
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public Integer getAgcProCertiStatus() {
		return agcProCertiStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_professional.agcProCertiStatus
	 * 
	 * @param agcProCertiStatus
	 *            the value for agc_professional.agcProCertiStatus
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public void setAgcProCertiStatus(Integer agcProCertiStatus) {
		this.agcProCertiStatus = agcProCertiStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_professional.agcProOtherCertis
	 * 
	 * @return the value of agc_professional.agcProOtherCertis
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public Date getAgcProOtherCertis() {
		return agcProOtherCertis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_professional.agcProOtherCertis
	 * 
	 * @param agcProOtherCertis
	 *            the value for agc_professional.agcProOtherCertis
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public void setAgcProOtherCertis(Date agcProOtherCertis) {
		this.agcProOtherCertis = agcProOtherCertis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_professional.agcProRewdPunish
	 * 
	 * @return the value of agc_professional.agcProRewdPunish
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public String getAgcProRewdPunish() {
		return agcProRewdPunish;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_professional.agcProRewdPunish
	 * 
	 * @param agcProRewdPunish
	 *            the value for agc_professional.agcProRewdPunish
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public void setAgcProRewdPunish(String agcProRewdPunish) {
		this.agcProRewdPunish = agcProRewdPunish == null ? null : agcProRewdPunish.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column agc_professional.agcProResume
	 * 
	 * @return the value of agc_professional.agcProResume
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public String getAgcProResume() {
		return agcProResume;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column agc_professional.agcProResume
	 * 
	 * @param agcProResume
	 *            the value for agc_professional.agcProResume
	 * 
	 * @mbggenerated Tue Nov 13 22:33:48 GMT+08:00 2012
	 */
	public void setAgcProResume(String agcProResume) {
		this.agcProResume = agcProResume == null ? null : agcProResume.trim();
	}

	public String getAgcCnName() {
		return agcCnName;
	}

	public void setAgcCnName(String agcCnName) {
		this.agcCnName = agcCnName;
	}

	public String getAgcProId() {
		return agcProId;
	}

	public void setAgcProId(String agcProId) {
		this.agcProId = agcProId;
	}

	public String getAgcId() {
		return agcId;
	}

	public void setAgcId(String agcId) {
		this.agcId = agcId;
	}
}