package com.credit.model.rate;

import java.util.Date;

public class Firm {

	private String firmId;

	private String firmOrgId;

	private String firmCnName;

	private String firmEnName;

	private Integer firmNature;

	private String firmRegisAddr;

	private Integer firmMunicpPrv;

	private Integer firmMunicpCity;

	private Integer firmMunicpDistr;

	private String firmPostalAddr;

	private String firmLegleRepre;

	private String firmPrincipalName;

	private String firmContactNumber;

	private String firmFax;

	private Integer firmRegisType;

	private String firmRagisNum;

	private Date firmRagisDate;

	private Date firmBizLicnsExpDate;

	private String firmNTaxCertiNum;

	private String firmLTaxCertiNum;

	private String firmLoanCardCode;

	private String firmIndustryType;

	private String firmWebsite;

	private Integer firmListedLoac;

	private String firmListedCode;

	private String firmFeature;

	private Integer firmCrewSize;

	private String firmBizScope;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmOrgId
	 * 
	 * @return the value of firm_base_info.firmOrgId
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public String getFirmOrgId() {
		return firmOrgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmOrgId
	 * 
	 * @param firmOrgId
	 *            the value for firm_base_info.firmOrgId
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmOrgId(String firmOrgId) {
		this.firmOrgId = firmOrgId == null ? null : firmOrgId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmCnName
	 * 
	 * @return the value of firm_base_info.firmCnName
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public String getFirmCnName() {
		return firmCnName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmCnName
	 * 
	 * @param firmCnName
	 *            the value for firm_base_info.firmCnName
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmCnName(String firmCnName) {
		this.firmCnName = firmCnName == null ? null : firmCnName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmEnName
	 * 
	 * @return the value of firm_base_info.firmEnName
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public String getFirmEnName() {
		return firmEnName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmEnName
	 * 
	 * @param firmEnName
	 *            the value for firm_base_info.firmEnName
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmEnName(String firmEnName) {
		this.firmEnName = firmEnName == null ? null : firmEnName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmNature
	 * 
	 * @return the value of firm_base_info.firmNature
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public Integer getFirmNature() {
		return firmNature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmNature
	 * 
	 * @param firmNature
	 *            the value for firm_base_info.firmNature
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmNature(Integer firmNature) {
		this.firmNature = firmNature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmRegisAddr
	 * 
	 * @return the value of firm_base_info.firmRegisAddr
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public String getFirmRegisAddr() {
		return firmRegisAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmRegisAddr
	 * 
	 * @param firmRegisAddr
	 *            the value for firm_base_info.firmRegisAddr
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmRegisAddr(String firmRegisAddr) {
		this.firmRegisAddr = firmRegisAddr == null ? null : firmRegisAddr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmMunicpPrv
	 * 
	 * @return the value of firm_base_info.firmMunicpPrv
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public Integer getFirmMunicpPrv() {
		return firmMunicpPrv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmMunicpPrv
	 * 
	 * @param firmMunicpPrv
	 *            the value for firm_base_info.firmMunicpPrv
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmMunicpPrv(Integer firmMunicpPrv) {
		this.firmMunicpPrv = firmMunicpPrv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmMunicpCity
	 * 
	 * @return the value of firm_base_info.firmMunicpCity
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public Integer getFirmMunicpCity() {
		return firmMunicpCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmMunicpCity
	 * 
	 * @param firmMunicpCity
	 *            the value for firm_base_info.firmMunicpCity
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmMunicpCity(Integer firmMunicpCity) {
		this.firmMunicpCity = firmMunicpCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmMunicpDistr
	 * 
	 * @return the value of firm_base_info.firmMunicpDistr
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public Integer getFirmMunicpDistr() {
		return firmMunicpDistr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmMunicpDistr
	 * 
	 * @param firmMunicpDistr
	 *            the value for firm_base_info.firmMunicpDistr
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmMunicpDistr(Integer firmMunicpDistr) {
		this.firmMunicpDistr = firmMunicpDistr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmPostalAddr
	 * 
	 * @return the value of firm_base_info.firmPostalAddr
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public String getFirmPostalAddr() {
		return firmPostalAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmPostalAddr
	 * 
	 * @param firmPostalAddr
	 *            the value for firm_base_info.firmPostalAddr
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmPostalAddr(String firmPostalAddr) {
		this.firmPostalAddr = firmPostalAddr == null ? null : firmPostalAddr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmLegleRepre
	 * 
	 * @return the value of firm_base_info.firmLegleRepre
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public String getFirmLegleRepre() {
		return firmLegleRepre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmLegleRepre
	 * 
	 * @param firmLegleRepre
	 *            the value for firm_base_info.firmLegleRepre
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmLegleRepre(String firmLegleRepre) {
		this.firmLegleRepre = firmLegleRepre == null ? null : firmLegleRepre.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmPrincipalName
	 * 
	 * @return the value of firm_base_info.firmPrincipalName
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public String getFirmPrincipalName() {
		return firmPrincipalName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmPrincipalName
	 * 
	 * @param firmPrincipalName
	 *            the value for firm_base_info.firmPrincipalName
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmPrincipalName(String firmPrincipalName) {
		this.firmPrincipalName = firmPrincipalName == null ? null : firmPrincipalName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmContactNumber
	 * 
	 * @return the value of firm_base_info.firmContactNumber
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public String getFirmContactNumber() {
		return firmContactNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmContactNumber
	 * 
	 * @param firmContactNumber
	 *            the value for firm_base_info.firmContactNumber
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmContactNumber(String firmContactNumber) {
		this.firmContactNumber = firmContactNumber == null ? null : firmContactNumber.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmFax
	 * 
	 * @return the value of firm_base_info.firmFax
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public String getFirmFax() {
		return firmFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmFax
	 * 
	 * @param firmFax
	 *            the value for firm_base_info.firmFax
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmFax(String firmFax) {
		this.firmFax = firmFax == null ? null : firmFax.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmRegisType
	 * 
	 * @return the value of firm_base_info.firmRegisType
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public Integer getFirmRegisType() {
		return firmRegisType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmRegisType
	 * 
	 * @param firmRegisType
	 *            the value for firm_base_info.firmRegisType
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmRegisType(Integer firmRegisType) {
		this.firmRegisType = firmRegisType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmRagisNum
	 * 
	 * @return the value of firm_base_info.firmRagisNum
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public String getFirmRagisNum() {
		return firmRagisNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmRagisNum
	 * 
	 * @param firmRagisNum
	 *            the value for firm_base_info.firmRagisNum
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmRagisNum(String firmRagisNum) {
		this.firmRagisNum = firmRagisNum == null ? null : firmRagisNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmRagisDate
	 * 
	 * @return the value of firm_base_info.firmRagisDate
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public Date getFirmRagisDate() {
		return firmRagisDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmRagisDate
	 * 
	 * @param firmRagisDate
	 *            the value for firm_base_info.firmRagisDate
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmRagisDate(Date firmRagisDate) {
		this.firmRagisDate = firmRagisDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmBizLicnsExpDate
	 * 
	 * @return the value of firm_base_info.firmBizLicnsExpDate
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public Date getFirmBizLicnsExpDate() {
		return firmBizLicnsExpDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmBizLicnsExpDate
	 * 
	 * @param firmBizLicnsExpDate
	 *            the value for firm_base_info.firmBizLicnsExpDate
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmBizLicnsExpDate(Date firmBizLicnsExpDate) {
		this.firmBizLicnsExpDate = firmBizLicnsExpDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmNTaxCertiNum
	 * 
	 * @return the value of firm_base_info.firmNTaxCertiNum
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public String getFirmNTaxCertiNum() {
		return firmNTaxCertiNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmNTaxCertiNum
	 * 
	 * @param firmNTaxCertiNum
	 *            the value for firm_base_info.firmNTaxCertiNum
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmNTaxCertiNum(String firmNTaxCertiNum) {
		this.firmNTaxCertiNum = firmNTaxCertiNum == null ? null : firmNTaxCertiNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmLTaxCertiNum
	 * 
	 * @return the value of firm_base_info.firmLTaxCertiNum
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public String getFirmLTaxCertiNum() {
		return firmLTaxCertiNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmLTaxCertiNum
	 * 
	 * @param firmLTaxCertiNum
	 *            the value for firm_base_info.firmLTaxCertiNum
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmLTaxCertiNum(String firmLTaxCertiNum) {
		this.firmLTaxCertiNum = firmLTaxCertiNum == null ? null : firmLTaxCertiNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmLoanCardCode
	 * 
	 * @return the value of firm_base_info.firmLoanCardCode
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public String getFirmLoanCardCode() {
		return firmLoanCardCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmLoanCardCode
	 * 
	 * @param firmLoanCardCode
	 *            the value for firm_base_info.firmLoanCardCode
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmLoanCardCode(String firmLoanCardCode) {
		this.firmLoanCardCode = firmLoanCardCode == null ? null : firmLoanCardCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmIndustryType
	 * 
	 * @return the value of firm_base_info.firmIndustryType
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public String getFirmIndustryType() {
		return firmIndustryType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmIndustryType
	 * 
	 * @param firmIndustryType
	 *            the value for firm_base_info.firmIndustryType
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmIndustryType(String firmIndustryType) {
		this.firmIndustryType = firmIndustryType == null ? null : firmIndustryType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmWebsite
	 * 
	 * @return the value of firm_base_info.firmWebsite
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public String getFirmWebsite() {
		return firmWebsite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmWebsite
	 * 
	 * @param firmWebsite
	 *            the value for firm_base_info.firmWebsite
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmWebsite(String firmWebsite) {
		this.firmWebsite = firmWebsite == null ? null : firmWebsite.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmListedLoac
	 * 
	 * @return the value of firm_base_info.firmListedLoac
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public Integer getFirmListedLoac() {
		return firmListedLoac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmListedLoac
	 * 
	 * @param firmListedLoac
	 *            the value for firm_base_info.firmListedLoac
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmListedLoac(Integer firmListedLoac) {
		this.firmListedLoac = firmListedLoac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmListedCode
	 * 
	 * @return the value of firm_base_info.firmListedCode
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public String getFirmListedCode() {
		return firmListedCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmListedCode
	 * 
	 * @param firmListedCode
	 *            the value for firm_base_info.firmListedCode
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmListedCode(String firmListedCode) {
		this.firmListedCode = firmListedCode == null ? null : firmListedCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmFeature
	 * 
	 * @return the value of firm_base_info.firmFeature
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public String getFirmFeature() {
		return firmFeature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmFeature
	 * 
	 * @param firmFeature
	 *            the value for firm_base_info.firmFeature
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmFeature(String firmFeature) {
		this.firmFeature = firmFeature == null ? null : firmFeature.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmCrewSize
	 * 
	 * @return the value of firm_base_info.firmCrewSize
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public Integer getFirmCrewSize() {
		return firmCrewSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmCrewSize
	 * 
	 * @param firmCrewSize
	 *            the value for firm_base_info.firmCrewSize
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmCrewSize(Integer firmCrewSize) {
		this.firmCrewSize = firmCrewSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column firm_base_info.firmBizScope
	 * 
	 * @return the value of firm_base_info.firmBizScope
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public String getFirmBizScope() {
		return firmBizScope;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column firm_base_info.firmBizScope
	 * 
	 * @param firmBizScope
	 *            the value for firm_base_info.firmBizScope
	 * 
	 * @mbggenerated Sat Nov 03 15:46:57 GMT+08:00 2012
	 */
	public void setFirmBizScope(String firmBizScope) {
		this.firmBizScope = firmBizScope == null ? null : firmBizScope.trim();
	}

	public String getFirmId() {
		return firmId;
	}

	public void setFirmId(String firmId) {
		this.firmId = firmId;
	}
}